### ISSUE TITLE
下载模型需要访问权限

### ISSUE THREAD

**Issue by bychen7** [HalbertCH/IEContraAST#1]
两个模型都需要访问权限，可以给个权限吗？谢谢。

<img width="638" alt="截屏2021-12-03 11 01 02" src="https://user-images.githubusercontent.com/55865490/144537845-1c60bcb1-4fb4-4795-8602-bda2036415b0.png">

**Comment by HalbertCH** [comment]
不好意思前面权限设置的有点问题，目前已修改，你可以再访问试试。

**Comment by bychen7** [comment]
> 不好意思前面权限设置的有点问题，目前已修改，你可以再访问试试。

解决了，谢谢~
